Update run_once_20_install-manjaro-desktop-packages.sh.tmpl

diff --git a/.chezmoiscripts/run_once_20_install-manjaro-desktop-packages.sh.tmpl b/.chezmoiscripts/run_once_20_install-manjaro-desktop-packages.sh.tmpl
--- a/.chezmoiscripts/run_once_20_install-manjaro-desktop-packages.sh.tmpl
+++ b/.chezmoiscripts/run_once_20_install-manjaro-desktop-packages.sh.tmpl
@@ -1,3 +1,5 @@
+#!/bin/bash
+set -e # Exit on error
 {{- if (and (eq .chezmoi.osRelease.id "manjaro") (.isServer))}}
 
 {{ $pacman_packages := list
@@ -29,9 +31,6 @@
 {{  $sudo = "" -}}
 {{ end -}}
 
-#!/bin/sh
-
-set -e # Exit on error
 
 printf '\nUpdating pacman packages. Root privileges needed.\n'
 {{ $sudo }} pacman -Syu --needed {{ $pacman_packages | join " " }}
